package appPackages;
import client.LoginForm;
import com.sun.glass.events.KeyEvent;
import java.sql.*;
import java.awt.Color;
import java.net.*;
import static java.lang.Thread.sleep;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.util.Calendar;
import java.util.Enumeration;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pitchtalk1.pkg1.DBConnection;

public class Home extends javax.swing.JFrame {

    public boolean mainOpen = false;
    DBConnection db = new DBConnection();

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setTitle("PitchTalk");
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        this.pack();
        chat_btn.setEnabled(false);
        chatRoom_btn.setEnabled(false);
        jMenuItem5.setEnabled(false);
        jMenuItem3.setEnabled(false);
        cutMenuItem.setEnabled(false);
       sendBtn_.setEnabled(false);
       noCon.setVisible(false);
       conActive.setVisible(false);
       sendBtn_.setVisible(false);
        CurrentDate();
        LANST();
        
        this.setSize(450, 335);
        jPanel2.hide();
        
    }
    private void CurrentDate(){
       Thread clock = new Thread(){
            @Override
            public void run(){
                for(;;){
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        jMenu3.setText((day + "/" +(month+1+"/"+year)));
        
        int seconds = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        jMenu4.setText((hour + ":" + (minute)+":"+seconds));
                    try {
                        sleep(1000);
                    } catch (InterruptedException ex) {
                        
                    }
                    
                }
            }                 
        };clock.start();
    }
    
    private void LANST(){
        Socket sock = new Socket();
        InetSocketAddress addr = new InetSocketAddress("www.google.com",80);
        try{
            sock.connect(addr,3000);
            conStatus.setVisible(true);
            conStatus.setText("LAN Connection Available");
            conActive.setVisible(true);
            conStatus.setBackground(Color.green);
            
        } catch (Exception e) {
            conStatus.setVisible(true);
            conStatus.setBackground(Color.red);
            conStatus.setText("No LAN Connection");
            noCon.setVisible(true);
        }finally{
            try{sock.close();}
            catch(Exception e){}
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        sendBtn_ = new javax.swing.JButton();
        chat_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pfPass = new javax.swing.JPasswordField();
        tfUser = new javax.swing.JTextField();
        clearbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        logbtn = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        twitterIco = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        chatRoom_btn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        signoutMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        cutMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        conActive = new javax.swing.JMenu();
        noCon = new javax.swing.JMenu();
        conStatus = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("DokChampa", 0, 10)); // NOI18N
        setForeground(new java.awt.Color(102, 102, 102));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        sendBtn_.setBackground(new java.awt.Color(255, 255, 255));
        sendBtn_.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 36)); // NOI18N
        sendBtn_.setToolTipText("Send Learning material(Ctrl+S)");
        sendBtn_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendBtn_.setLabel("");
        sendBtn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtn_ActionPerformed(evt);
            }
        });

        chat_btn.setBackground(new java.awt.Color(255, 255, 255));
        chat_btn.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 24)); // NOI18N
        chat_btn.setText("");
        chat_btn.setToolTipText("Communicate via LAN(Ctrl+C)");
        chat_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chat_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chat_btnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe MDL2 Assets", 0, 18))); // NOI18N
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel1.setText("Nickname");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel2.setText("Password");

        pfPass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pfPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pfPassMouseClicked(evt);
            }
        });
        pfPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfPassKeyPressed(evt);
            }
        });

        tfUser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        clearbtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.setToolTipText("Delete everything you've typed in the textboxes");
        clearbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel3.setText("Create Credential(?)");
        jLabel3.setToolTipText("Create a free account");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        logbtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        logbtn.setToolTipText("");
        logbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logbtn.setLabel("Login");
        logbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logbtnActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Developed for Kumasi Polytechnic");

        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("By Ken Boamponsem");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfUser))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(logbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(clearbtn))
                                    .addComponent(pfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(49, 49, 49))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(31, 31, 31))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("File Transfer"));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel6.setText("Select File To Transfer");

        jTextField2.setText("File Path");
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField2.setEnabled(false);

        jButton6.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jButton6.setText("Browse");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel7.setText("Send To");

        jTextField3.setText("000.00.0.0");
        jTextField3.setToolTipText("Destination IP Address");
        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField3CaretUpdate(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jButton7.setText("Cancel");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jButton8.setText("Send");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jButton8))
                    .addComponent(jButton6)
                    .addComponent(jTextField3)
                    .addComponent(jTextField2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        twitterIco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appPackages/twitter_circle_black-512.png"))); // NOI18N
        twitterIco.setToolTipText("Follow developer on twitter");
        twitterIco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        twitterIco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                twitterIcoMousePressed(evt);
            }
        });

        jLabel10.setText("Version 1.2");

        chatRoom_btn.setBackground(new java.awt.Color(255, 255, 255));
        chatRoom_btn.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 36)); // NOI18N
        chatRoom_btn.setToolTipText("Enter chatroom");
        chatRoom_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chatRoom_btn.setLabel("");
        chatRoom_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatRoom_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(sendBtn_, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chatRoom_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(chat_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(twitterIco)
                        .addGap(15, 15, 15)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(chat_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sendBtn_, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chatRoom_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(twitterIco)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(9, 9, 9)))))
                .addGap(26, 26, 26))
        );

        jMenu1.setText("File");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appPackages/chatbubble-working(1).png"))); // NOI18N
        jMenuItem3.setText("Chat");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Send");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setText("Exit");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        signoutMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        signoutMenu.setText("Back");
        signoutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutMenuActionPerformed(evt);
            }
        });
        jMenu1.add(signoutMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem1.setText("What is my IP");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("PitchTalk");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        cutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Edit or Delete Credentials");
        cutMenuItem.setToolTipText("");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(cutMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Date");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Time");
        jMenuBar1.add(jMenu4);

        conActive.setText("");
        conActive.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 12)); // NOI18N
        jMenuBar1.add(conActive);

        noCon.setText("");
        noCon.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 12)); // NOI18N
        jMenuBar1.add(noCon);

        conStatus.setText("Connection Status");
        conStatus.setToolTipText("Indicates if you have LAN connection");
        jMenuBar1.add(conStatus);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        // TODO add your handling code here:
        tfUser.setText("");
        pfPass.setText("");
        tfUser.requestFocus();
  
    }//GEN-LAST:event_clearbtnActionPerformed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        Credentials credentials = new Credentials();
        credentials.show();
        this.hide();
    }//GEN-LAST:event_jLabel3MousePressed

    private void sendBtn_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtn_ActionPerformed
        // TODO add your handling code here:
        this.setSize(500, 300);
        jPanel1.hide();
        jPanel2.show();
        jTextField3.requestFocus();
        twitterIco.setVisible(false);
       
    }//GEN-LAST:event_sendBtn_ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
//        this.setSize(500, 285);
//        jPanel1.hide();
//        jPanel2.show();
        this.setSize(500, 300);
        jPanel1.hide();
        jPanel2.show();
        jTextField3.requestFocus();
        twitterIco.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
//        Close close = new Close();
//        close.show();
        int i = JOptionPane.showConfirmDialog(this, "ARE YOU SURE YOU WANT TO CLOSE?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(i == JOptionPane.YES_OPTION){
//            new HomeBrowse().show();
//            this.hide();
            System.exit(0);
        }
        else{
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
//        int i = JOptionPane.showConfirmDialog(this, "ARE YOU SURE YOU WANT TO CLOSE?", "Confirm", JOptionPane.YES_NO_OPTION);
//        if(i == JOptionPane.YES_OPTION){
//            System.exit(0);
//        }
//        else{
//            jTextField1.requestFocus();
//        }
    }//GEN-LAST:event_formWindowClosing

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try{
            if(!(jTextField3.getText().length() >0)){
        jPanel1.show();
        jPanel2.hide();
        tfUser.requestFocus();
        }
            else{
        int i = JOptionPane.showConfirmDialog(this, "ARE YOU SURE YOU WANT TO CANCEL?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(i == JOptionPane.YES_OPTION){
        jPanel1.show();
//        jPanel1.setSize(400, 335);
        jPanel2.hide();
        tfUser.requestFocus();
        }
        else if(i == JOptionPane.NO_OPTION){
                    }           
            }
            
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
//        jMenuItem7.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1FocusGained

    private void jTextField3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField3CaretUpdate
        // TODO add your handling code here:
        jTextField3.setText("");
    }//GEN-LAST:event_jTextField3CaretUpdate

    private void logbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logbtnActionPerformed
        // TODO add your handling code here:
        if(!"Signout".equals(logbtn.getText())){
//            jButton4.setToolTipText("Click to Sign out");
       String sPass= null;
       try{
            String s= "select Password from Login where Nickname= '"+
                    tfUser.getText().trim()+"'";
            ResultSet rs = db.stmt.executeQuery(s);
            while (rs.next()){
                sPass = rs.getString("Password");
            }      
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "User not found");
            Credentials credentials = new Credentials();
            credentials.show();
            dispose();
        }
         if (pfPass.getText().trim().equals(sPass.trim())){
             logbtn.setText("Signout");
             jMenu1.setEnabled(true);
             chat_btn.setEnabled(true);
             cutMenuItem.setEnabled(true);
             signoutMenu.setEnabled(true);
        jMenuItem5.setEnabled(true);
        jMenuItem3.setEnabled(true);
        cutMenuItem.setEnabled(true);
        sendBtn_.setEnabled(true);
        jLabel1.setEnabled(false);
        jLabel2.setEnabled(false);
        tfUser.setEnabled(false);
        pfPass.setEnabled(false);
        clearbtn.setEnabled(false);
        jLabel3.setVisible(false);  
        chatRoom_btn.setEnabled(true);
        }else{
             getToolkit().beep();
             pfPass.requestFocus();
            JOptionPane.showMessageDialog(this, "RE-ENTER PASSWORD", "WRONG PASSWORD", JOptionPane.ERROR_MESSAGE);
            pfPass.setText("");
            
//            Credentials credentials = new Credentials();
//        credentials.show();
//        this.hide();
        }
        }else{
            logbtn.setText("Login");
            logbtn.setToolTipText("Click to login");
            chat_btn.setEnabled(false);
        jMenuItem3.setEnabled(false);
        cutMenuItem.setEnabled(false);
        sendBtn_.setEnabled(false);
        jLabel1.setEnabled(true);
        jLabel2.setEnabled(true);
        tfUser.setEnabled(true);
        pfPass.setEnabled(true);
        clearbtn.setEnabled(true);
        jLabel3.setVisible(true);
        pfPass.setText("");
        pfPass.requestFocus();
       signoutMenu.setEnabled(false);
       chatRoom_btn.setEnabled(false);
        }   
    }//GEN-LAST:event_logbtnActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
//JOptionPane.showConfirmDialog(this, "YOUR IP ADDRESS IS "+pitchtalk1.pkg1.ipClass.ipAddress, "IP ADDRESS",JOptionPane.INFORMATION_MESSAGE);
        try {
            // TODO add your handling code here:
              InetAddress ip = InetAddress.getLocalHost();
//              JOptionPane.showConfirmDialog(this, "YOUR IP ADDRESS IS"+ip.getHostAddress(), "IP ADDRESS",JOptionPane.INFORMATION_MESSAGE);
              
           JOptionPane.showMessageDialog(this, "YOUR IP ADDRESS IS "+ip.getHostAddress());
            Enumeration e = NetworkInterface.getNetworkInterfaces();
            while(e.hasMoreElements()){
                NetworkInterface n = (NetworkInterface) e.nextElement();
                Enumeration ee = n.getInetAddresses();
                while(ee.hasMoreElements()){
                    InetAddress i = (InetAddress) ee.nextElement();
                    System.out.println(i.getHostAddress());
                }
                
            }

        } catch (Exception ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
//        try {
//         Enumeration e = NetworkInterface.getNetworkInterfaces();
// 
//         while(e.hasMoreElements()) {
//            NetworkInterface ni = (NetworkInterface) e.nextElement();
//            System.out.println("Net interface: "+ni.getName());
// 
//            Enumeration e2 = ni.getInetAddresses();
// 
//            while (e2.hasMoreElements()){
//               InetAddress ip = (InetAddress) e2.nextElement();
////               System.out.println("IP address: "+ ip.toString());
//               JOptionPane.showMessageDialog(this, "YOUR IP ADDRESS IS "+ip.toString());
//            }
//         }
//      }
//      catch (Exception e) {
//         e.printStackTrace();
//      }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACKSPACE) || c==KeyEvent.VK_DELETE || c==KeyEvent.VK_PERIOD)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void pfPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pfPassMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPassMouseClicked

    private void pfPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfPassKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(!"Signout".equals(logbtn.getText())){
//            jButton4.setToolTipText("Click to Sign out");
       String sPass= null;
       try{
            String s= "select Password from Login where Nickname= '"+
                    tfUser.getText().trim()+"'";
            ResultSet rs = db.stmt.executeQuery(s);
            while (rs.next()){
                sPass = rs.getString("Password");
            }      
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "User not found");
            Credentials credentials = new Credentials();
            credentials.show();
            dispose();
        }
         if (pfPass.getText().trim().equals(sPass.trim())){
             logbtn.setText("Signout");
             chat_btn.setEnabled(true);
             cutMenuItem.setEnabled(true);
        jMenuItem5.setEnabled(true);
        jMenuItem3.setEnabled(true);
        sendBtn_.setEnabled(true);
        jLabel1.setEnabled(false);
        jLabel2.setEnabled(false);
        tfUser.setEnabled(false);
        pfPass.setEnabled(false);
        clearbtn.setEnabled(false);
        jLabel3.setVisible(false);  
        chatRoom_btn.setEnabled(true);
        }else{
             getToolkit().beep();
             pfPass.requestFocus();
            JOptionPane.showMessageDialog(this, "RE-ENTER PASSWORD", "WRONG PASSWORD", JOptionPane.ERROR_MESSAGE);
            pfPass.selectAll();
            
//            Credentials credentials = new Credentials();
//        credentials.show();
//        this.hide();
        }
        }else{
            logbtn.setText("Login");
            logbtn.setToolTipText("Click to login");
            chat_btn.setEnabled(false);
        jMenuItem5.setEnabled(false);
        jMenuItem3.setEnabled(false);
        sendBtn_.setEnabled(false);
        jLabel1.setEnabled(true);
        jLabel2.setEnabled(true);
        tfUser.setEnabled(true);
        pfPass.setEnabled(true);
        clearbtn.setEnabled(true);
        jLabel3.setVisible(true);
        tfUser.setText("");
        pfPass.setText("");
       tfUser.requestFocus();        
        }     
        }
    }//GEN-LAST:event_pfPassKeyPressed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void chat_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chat_btnActionPerformed
        // TODO add your handling code here:
//        if(!mainOpen){
//            MainScreen mainScreen = new MainScreen();
//            mainScreen.setVisible(true);
//            mainScreen.setFocusableWindowState(true);
//            mainOpen = true;
//        }
//        else{
//            getToolkit().beep();
//        }
        dispose();
//        this.setSize(550, 647);
         MainScreen mainScreen = new MainScreen();
         mainScreen.setSize(550, 647);
        mainScreen.show();
//        new MainScreen().Name.setText(this.tfUser.getText());
        
        
    }//GEN-LAST:event_chat_btnActionPerformed

    private void signoutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutMenuActionPerformed
        // TODO add your handling code here:
        dispose();
        new HomeBrowse().show();
    }//GEN-LAST:event_signoutMenuActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new MainScreen().show();
        hide();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        // TODO add your handling code here:
        if(!cutMenuItem.isEnabled()){
            cutMenuItem.setToolTipText("You must be logged in first");
        }else{
            cutMenuItem.setToolTipText("Delete your credentials");
        }
        this.dispose();
        try {
            new DeleteCred().show();
            
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
//        client.AttachmentForm send = new AttachmentForm();
//        send.show();
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void twitterIcoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twitterIcoMousePressed
        // TODO add your handling code here:
            if(conStatus.getText().equals("LAN Connection Available")){
                        try {
            String URL ="https://twitter.com/KhanWest_gh";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
            }else{
                JOptionPane.showMessageDialog(this, "THIS DEVICE ISN'T CONNECTED TO THE INTERNET", "WARNING", JOptionPane.WARNING_MESSAGE);
            }

    }//GEN-LAST:event_twitterIcoMousePressed

    private void chatRoom_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatRoom_btnActionPerformed
        // TODO add your handling code here:
        dispose();
        client.LoginForm login = new LoginForm();
        login.show();
    }//GEN-LAST:event_chatRoom_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
//                UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chatRoom_btn;
    private javax.swing.JButton chat_btn;
    private javax.swing.JButton clearbtn;
    private javax.swing.JMenu conActive;
    private javax.swing.JMenu conStatus;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToggleButton logbtn;
    private javax.swing.JMenu noCon;
    private javax.swing.JPasswordField pfPass;
    private javax.swing.JButton sendBtn_;
    private javax.swing.JMenuItem signoutMenu;
    public static javax.swing.JTextField tfUser;
    private javax.swing.JLabel twitterIco;
    // End of variables declaration//GEN-END:variables
}
