//Notes for project
/*System should be able to send a message
Socket, target port
connect
 * Receive a message
Server,receiving port
 * 
 * 
 */
package appPackages;

import chatapp.networking.MessageListener;
import chatapp.networking.MessageTransmitter;
import chatapp.networking.WritableGUI;
import com.sun.glass.events.KeyEvent;
import client.*;
import java.awt.Color;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class MainScreen extends javax.swing.JFrame implements WritableGUI{
//    SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
//    File file;

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        setLocationRelativeTo(this);
        this.setSize(550, 647);
        this.getContentPane().setBackground(Color.WHITE);
        setTitle("Private Chat");
        cancelButton.setVisible(false);
        hideMenu.setVisible(false);
        setTitle("YOU'RE SIGNED IN ON " + new MainScreen.NetInfo().say());
        jLabel3.setText(new MainScreen.NetInfo().say());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        chat = new javax.swing.JTextArea();
        message = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        listenButton = new javax.swing.JButton();
        receivePort = new javax.swing.JTextField();
        ipTextField = new javax.swing.JTextField();
        targetPort = new javax.swing.JTextField();
        screenIcon = new javax.swing.JLabel();
        sendIcon = new javax.swing.JLabel();
        chatRoomIcon = new javax.swing.JLabel();
        closeShutIcon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        userName = new javax.swing.JTextField();
        timeZone = new javax.swing.JTextField();
        pNum = new javax.swing.JTextField();
        eMail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        HoverBar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        hideMenu = new javax.swing.JMenuItem();
        unHide = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Berlin Sans FB", 0, 10)); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        chat.setEditable(false);
        chat.setBackground(new java.awt.Color(0, 0, 0));
        chat.setColumns(20);
        chat.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        chat.setForeground(new java.awt.Color(0, 255, 255));
        chat.setRows(5);
        jScrollPane1.setViewportView(chat);

        message.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                messageCaretUpdate(evt);
            }
        });
        message.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                messageMouseMoved(evt);
            }
        });
        message.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                messageMouseExited(evt);
            }
        });
        message.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                messageKeyPressed(evt);
            }
        });

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        listenButton.setText("Listen");
        listenButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listenButtonActionPerformed(evt);
            }
        });

        receivePort.setText("8877");
        receivePort.setToolTipText("Listening Port");
        receivePort.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                receivePortMouseMoved(evt);
            }
        });
        receivePort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                receivePortMouseExited(evt);
            }
        });
        receivePort.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                receivePortKeyTyped(evt);
            }
        });

        ipTextField.setToolTipText("IP Address");
        ipTextField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ipTextFieldMouseMoved(evt);
            }
        });
        ipTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ipTextFieldMouseExited(evt);
            }
        });

        targetPort.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                targetPortMouseMoved(evt);
            }
        });
        targetPort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                targetPortMouseExited(evt);
            }
        });
        targetPort.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                targetPortKeyTyped(evt);
            }
        });

        screenIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appPackages/SCREENSHOT.png"))); // NOI18N
        screenIcon.setToolTipText("Take screenshot of message");
        screenIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        screenIcon.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                screenIconMouseMoved(evt);
            }
        });
        screenIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                screenIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                screenIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                screenIconMouseExited(evt);
            }
        });

        sendIcon.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        sendIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appPackages/mail-flat.png"))); // NOI18N
        sendIcon.setToolTipText("Send File");
        sendIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendIcon.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                sendIconMouseMoved(evt);
            }
        });
        sendIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sendIconMouseExited(evt);
            }
        });

        chatRoomIcon.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        chatRoomIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kenny\\Documents\\chat.png")); // NOI18N
        chatRoomIcon.setToolTipText("Join Chatroom");
        chatRoomIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chatRoomIcon.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                chatRoomIconMouseMoved(evt);
            }
        });
        chatRoomIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatRoomIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chatRoomIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                chatRoomIconMouseExited(evt);
            }
        });

        closeShutIcon.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        closeShutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appPackages/Sign-out_flat-circle-white-on-red_512x512.png"))); // NOI18N
        closeShutIcon.setToolTipText("Closes app and shuts down PC");
        closeShutIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeShutIcon.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                closeShutIconMouseMoved(evt);
            }
        });
        closeShutIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeShutIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeShutIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeShutIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(listenButton)
                        .addGap(27, 27, 27)
                        .addComponent(receivePort, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(screenIcon)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sendIcon)
                        .addGap(72, 72, 72)
                        .addComponent(chatRoomIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeShutIcon))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(targetPort, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(closeShutIcon)
                    .addComponent(screenIcon)
                    .addComponent(sendIcon)
                    .addComponent(chatRoomIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listenButton)
                    .addComponent(receivePort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(targetPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel1.setText("Username");
        jLabel1.setToolTipText("Click to change your username");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel7.setText("Timezone");

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel8.setText("Phone number");

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel9.setText("Email");

        editButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        userName.setEditable(false);

        timeZone.setEditable(false);

        pNum.setEditable(false);

        eMail.setEditable(false);

        jLabel10.setText("Full Name");

        jLabel11.setText("Position");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Profile pic"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        cancelButton.setText("Cancel");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userName))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timeZone))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pNum))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cancelButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5))
                                    .addComponent(eMail)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(timeZone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(pNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(eMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel8)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton)
                    .addComponent(cancelButton))
                .addGap(16, 16, 16))
        );

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel12.setText("Sign out (?)");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });

        HoverBar.setEditable(false);
        HoverBar.setForeground(new java.awt.Color(22, 30, 30));
        HoverBar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HoverBar.setBorder(null);
        HoverBar.setOpaque(false);
        HoverBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoverBarActionPerformed(evt);
            }
        });

        jButton1.setText("...");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("YOUR IP ADDRESS IS");

        jLabel3.setText("IP");

        jLabel4.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 12)); // NOI18N
        jLabel4.setText("");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("View IP Address");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Listen");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        hideMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        hideMenu.setText("Hide Side Bar");
        hideMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideMenuActionPerformed(evt);
            }
        });
        jMenu1.add(hideMenu);

        unHide.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        unHide.setText("Unhide Bar");
        unHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unHideActionPerformed(evt);
            }
        });
        jMenu1.add(unHide);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setText("Go to home view (?)");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setText("Post Announcement");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem3.setText("Quick Help");
        jMenu2.add(jMenuItem3);

        jMenu3.setText("How To");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setText("View Chat Buddy IP Address");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Screenshot");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Record");
        jMenu3.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem7.setText("Send File");
        jMenu3.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Join Chatroom");
        jMenu3.add(jMenuItem8);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem9.setText("Sign-out");
        jMenu3.add(jMenuItem9);

        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendButton))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(542, 542, 542)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(HoverBar)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel4))
                        .addGap(11, 11, 11)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendButton)
                    .addComponent(jButton1)
                    .addComponent(message))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HoverBar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

public class NetInfo {
 
     public String say() {
       try {
       java.net.InetAddress i = java.net.InetAddress.getLocalHost();
//       System.out.println(i);                  // name and IP address
       System.out.println(i.getHostName());    // name
//       System.out.println(i.getHostAddress()); // IP address only
       i.getHostAddress();
//       i.getHostName();
        return i.getHostAddress();
       }
       catch(Exception e){e.printStackTrace();}
       return null;
     }
    }
//public void appendMessage(String msg){
//        Date date = new Date();
//        chat.append(sdf.format(date) +": "+ msg +"\n");
//    }
//public class ip{
//    public void ip (){
//        ipTextField.setText(new MainScreen.NetInfo().say());
//        
//    }
//}
//ip= ipTextField.setText(new MainScreen.NetInfo().say());

    
    private void receivePortKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_receivePortKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACKSPACE) || c==KeyEvent.VK_DELETE )) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_receivePortKeyTyped

    private void targetPortKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_targetPortKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACKSPACE) || c==KeyEvent.VK_DELETE )) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_targetPortKeyTyped

    MessageListener listener;
    private void listenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listenButtonActionPerformed
        // TODO add your handling code here:
        listener = new MessageListener(this,Integer.parseInt(receivePort.getText()));
        listener.start();
        HoverBar.setText("Listening");
    }//GEN-LAST:event_listenButtonActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
        MessageTransmitter transmitter = new MessageTransmitter(message.getText(),ipTextField.getText(),Integer.parseInt(targetPort.getText()));
        transmitter.start();
        message.setText("");
        message.requestFocus();
    }//GEN-LAST:event_sendButtonActionPerformed

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        try {
            // TODO add your handling code here:
            DeleteCred deletecred = new DeleteCred();
            while (deletecred.isActive()) { 
                new MainScreen().disable();               
            }
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_jLabel1MouseReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
//        ipTextField.requestFocusInWindow();
//        ipTextField.setText(pitchtalk1.pkg1.ipClass.ipAddress);
        message.requestFocusInWindow();
    }//GEN-LAST:event_formWindowOpened

    private void closeShutIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeShutIconMouseClicked
        // TODO add your handling code here:
        getToolkit().beep();
        int i = JOptionPane.showConfirmDialog(this, "THIS WILL CLOSE ALL APPS AND SHUT DOWN PC \n CONTINUE?", "WARNING !", JOptionPane.YES_NO_OPTION);
        if(i == JOptionPane.YES_OPTION){
            Runtime runtime = Runtime.getRuntime();
            try{
                Process proc = runtime.exec("shutdown -s -t 0");               
            }catch(Exception e){
                System.err.println();
            }
        
    }//GEN-LAST:event_closeShutIconMouseClicked
    }
    private void sendIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendIconMouseClicked
        // TODO add your handling code here:
        AttachmentForm form = new AttachmentForm();
        form.show();
//        disable();
    }//GEN-LAST:event_sendIconMouseClicked

    private void chatRoomIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatRoomIconMouseClicked
        // TODO add your handling code here:
        dispose();
        client.LoginForm login = new LoginForm();
        login.show();

    }//GEN-LAST:event_chatRoomIconMouseClicked

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        // TODO add your handling code here:
        dispose();
//        new HomeBrowse().show();
        new Home().show();
    }//GEN-LAST:event_jLabel12MousePressed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        userName.setEditable(true);
        userName.requestFocus();
        pNum.setEditable(true);
        eMail.setEditable(true);
        timeZone.setEditable(true);
        editButton.setText("Save");
        cancelButton.setVisible(true);
    }//GEN-LAST:event_editButtonActionPerformed

    private void screenIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_screenIconMouseClicked
        // TODO add your handling code here:
        try {
            Rectangle screenRect = new Rectangle(Toolkit.getDefaultToolkit().getScreenSize());
            BufferedImage capture = new Robot().createScreenCapture(screenRect);
            ImageIcon icon = new ImageIcon(capture);
            ImageIO.write(capture, "png", new File("C:\\Users\\Kenny\\Pictures\\PitchTalkScreenshot.png"));
            JOptionPane.showMessageDialog(this, "SCREENSHOT SAVED AT C:\\Users\\Kenny\\Pictures", "CAPTURED" ,JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_screenIconMouseClicked

    private void messageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_messageKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            MessageTransmitter transmitter = new MessageTransmitter(message.getText(),ipTextField.getText(),Integer.parseInt(targetPort.getText()));
        transmitter.start();
        message.setText("");
        message.requestFocus();
        }
    }//GEN-LAST:event_messageKeyPressed

    private void HoverBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoverBarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_HoverBarActionPerformed

    private void screenIconMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_screenIconMouseMoved
        // TODO add your handling code here:
        HoverBar.setText("Take screenshot of message");
    }//GEN-LAST:event_screenIconMouseMoved

    private void screenIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_screenIconMouseExited
        // TODO add your handling code here:
        HoverBar.setText("");
        ImageIcon ID = new ImageIcon(getClass().getResource("/appPackages/SCREENSHOT.png"));
        screenIcon.setIcon(ID);
    }//GEN-LAST:event_screenIconMouseExited

    private void sendIconMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendIconMouseMoved
        // TODO add your handling code here:
        HoverBar.setText("Send File");
    }//GEN-LAST:event_sendIconMouseMoved

    private void chatRoomIconMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatRoomIconMouseMoved
        // TODO add your handling code here:
        HoverBar.setText("Join Chatroom");
    }//GEN-LAST:event_chatRoomIconMouseMoved

    private void closeShutIconMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeShutIconMouseMoved
        // TODO add your handling code here:
        HoverBar.setText("Closes app and shuts down PC");
    }//GEN-LAST:event_closeShutIconMouseMoved

    private void sendIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendIconMouseExited
        // TODO add your handling code here:
        HoverBar.setText("");
        ImageIcon ID = new ImageIcon(getClass().getResource("/appPackages/mail-flat.png"));
        sendIcon.setIcon(ID);
    }//GEN-LAST:event_sendIconMouseExited

    private void chatRoomIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatRoomIconMouseExited
        // TODO add your handling code here:
        HoverBar.setText("");
        ImageIcon ID = new ImageIcon(getClass().getResource("/appPackages/chat.png"));
        chatRoomIcon.setIcon(ID);
    }//GEN-LAST:event_chatRoomIconMouseExited

    private void closeShutIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeShutIconMouseExited
        // TODO add your handling code here:
        HoverBar.setText("");
        ImageIcon ID = new ImageIcon(getClass().getResource("/appPackages/Sign-out_flat-circle-white-on-red_512x512.png"));
        closeShutIcon.setIcon(ID);
    }//GEN-LAST:event_closeShutIconMouseExited

    private void ipTextFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ipTextFieldMouseMoved
        // TODO add your handling code here:
        HoverBar.setText("Enter Receipient's IP Address");
    }//GEN-LAST:event_ipTextFieldMouseMoved

    private void ipTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ipTextFieldMouseExited
        // TODO add your handling code here:
        HoverBar.setText("");
    }//GEN-LAST:event_ipTextFieldMouseExited

    private void targetPortMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_targetPortMouseMoved
        // TODO add your handling code here:
        HoverBar.setText("Enter Receipient's port number");
    }//GEN-LAST:event_targetPortMouseMoved

    private void targetPortMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_targetPortMouseExited
        // TODO add your handling code here:
        HoverBar.setText("");
    }//GEN-LAST:event_targetPortMouseExited

    private void receivePortMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receivePortMouseMoved
        // TODO add your handling code here:
        HoverBar.setText("Enter your port number");
    }//GEN-LAST:event_receivePortMouseMoved

    private void receivePortMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receivePortMouseExited
        // TODO add your handling code here:
        HoverBar.setText("");
    }//GEN-LAST:event_receivePortMouseExited

    private void messageMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messageMouseMoved
        // TODO add your handling code here:
        HoverBar.setText("Enter message here then press enter to send");
    }//GEN-LAST:event_messageMouseMoved

    private void messageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messageMouseExited
        // TODO add your handling code here:
        HoverBar.setText("");
    }//GEN-LAST:event_messageMouseExited

    private void screenIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_screenIconMouseEntered
        // TODO add your handling code here:
        ImageIcon IC = new ImageIcon(getClass().getResource("/Images/screen.png"));
        screenIcon.setIcon(IC);
    }//GEN-LAST:event_screenIconMouseEntered

    private void sendIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendIconMouseEntered
        // TODO add your handling code here:
        ImageIcon ID = new ImageIcon(getClass().getResource("/Images/mail-icon.png"));
        sendIcon.setIcon(ID);
    }//GEN-LAST:event_sendIconMouseEntered

    private void chatRoomIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatRoomIconMouseEntered
        // TODO add your handling code here:
        ImageIcon ID = new ImageIcon(getClass().getResource("/Images/chat2.png"));
        chatRoomIcon.setIcon(ID);
    }//GEN-LAST:event_chatRoomIconMouseEntered

    private void closeShutIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeShutIconMouseEntered
        // TODO add your handling code here:
        ImageIcon ID = new ImageIcon(getClass().getResource("/Images/Sign-out.png"));
        closeShutIcon.setIcon(ID);
    }//GEN-LAST:event_closeShutIconMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        int browse = fileChooser.showOpenDialog(this);
//        if(browse == fileChooser.APPROVE_OPTION){
//            file = fileChooser.getSelectedFile();
//            txtFileURL.setText(file.getAbsolutePath());
//        }
        AttachmentForm form = new AttachmentForm();
        form.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void messageCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_messageCaretUpdate
        // TODO add your handling code here:
        if (message.getText().isEmpty()){
            sendButton.setEnabled(false);
        }else{
            sendButton.setEnabled(true);
        }
    }//GEN-LAST:event_messageCaretUpdate

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        listener = new MessageListener(this,Integer.parseInt(receivePort.getText()));
        listener.start();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void hideMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideMenuActionPerformed
        // TODO add your handling code here:
           this.setSize(550, 647);
           unHide.setVisible(true);
           hideMenu.setVisible(false);
       
    }//GEN-LAST:event_hideMenuActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        dispose();
//        new HomeBrowse().show();
        new Home().show();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void unHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unHideActionPerformed
        // TODO add your handling code here:
        this.setSize(811, 647);
           unHide.setVisible(false);
           hideMenu.setVisible(true);
    }//GEN-LAST:event_unHideActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        dispose();
        new HomeBrowse().show();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        new Message().show();
        dispose();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HoverBar;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextArea chat;
    private javax.swing.JLabel chatRoomIcon;
    private javax.swing.JLabel closeShutIcon;
    private javax.swing.JTextField eMail;
    private javax.swing.JButton editButton;
    private javax.swing.JMenuItem hideMenu;
    private javax.swing.JTextField ipTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listenButton;
    private javax.swing.JTextField message;
    private javax.swing.JTextField pNum;
    private javax.swing.JTextField receivePort;
    private javax.swing.JLabel screenIcon;
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel sendIcon;
    private javax.swing.JTextField targetPort;
    private javax.swing.JTextField timeZone;
    private javax.swing.JMenuItem unHide;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void write(String s) {
        chat.append(new MainScreen.NetInfo().say() + " > " + s +System.lineSeparator());
    }
}
