/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appPackages;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pitchtalk1.pkg1.DBConnection;

/**
 *
 * @author Kenny
 */
public class Message extends javax.swing.JFrame {
    DBConnection con = new DBConnection();

    /**
     * Creates new form Message
     */
    public Message() {
        initComponents();
        this.setSize(550, 345);
        this.setLocationRelativeTo(null);
        this.setTitle("ANNOUNCEMENTS");
        userName.setText(Home.tfUser.getText());
        String url = "jdbc:mysql://localhost/users";
        String user = "root";
        String password = "";        
        try {
            Connection conn = DriverManager.getConnection(url, user, password); 
            Statement myStmt = conn.createStatement();
            String sql1 = "select * from login where FirstName = '" + userName.getText()+"'";
                con.pst = conn.prepareStatement(sql1);
                con.rs=con.pst.executeQuery();
                if(con.rs.next()){
                    String add1 =con.rs.getString("Position");
                    positionTxt.setText(add1);
                    String add2 =con.rs.getString("FirstName");
                    userName.setText(add2);
                }                
        } catch (Exception e) {
            System.out.print(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FIELDArea = new javax.swing.JTextField();
        userName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        positionTxt = new javax.swing.JTextField();
        HoverBar = new javax.swing.JLabel();
        submitBtn = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        positionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        FIELDArea.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        FIELDArea.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        FIELDArea.setToolTipText("WRITE ANNOUNCEMENT HERE");
        FIELDArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        FIELDArea.setOpaque(false);
        getContentPane().add(FIELDArea);
        FIELDArea.setBounds(0, 100, 540, 130);

        userName.setEditable(false);
        userName.setOpaque(false);
        userName.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                userNameMouseMoved(evt);
            }
        });
        userName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userNameMouseExited(evt);
            }
        });
        getContentPane().add(userName);
        userName.setBounds(210, 20, 167, 20);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 30, 35, 16);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel2.setText("Credential");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 60, 60, 16);

        positionTxt.setOpaque(false);
        getContentPane().add(positionTxt);
        positionTxt.setBounds(210, 60, 170, 20);

        HoverBar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        HoverBar.setText("Help");
        getContentPane().add(HoverBar);
        HoverBar.setBounds(230, 290, 260, 16);

        submitBtn.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 36)); // NOI18N
        submitBtn.setText("");
        submitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                submitBtnMouseMoved(evt);
            }
        });
        submitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitBtnMouseExited(evt);
            }
        });
        getContentPane().add(submitBtn);
        submitBtn.setBounds(70, 240, 36, 36);

        cancelBtn.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 36)); // NOI18N
        cancelBtn.setText("");
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cancelBtnMouseMoved(evt);
            }
        });
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelBtnMouseExited(evt);
            }
        });
        getContentPane().add(cancelBtn);
        cancelBtn.setBounds(460, 240, 36, 36);

        jLabel10.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 36)); // NOI18N
        jLabel10.setText("");
        jLabel10.setToolTipText("Clear every field");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel10MouseMoved(evt);
            }
        });
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(260, 240, 36, 36);

        positionLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blue.jpg"))); // NOI18N
        positionLabel.setName(""); // NOI18N
        getContentPane().add(positionLabel);
        positionLabel.setBounds(0, 0, 540, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseMoved
        // TODO add your handling code here:
        HoverBar.setText("Reset");
    }//GEN-LAST:event_jLabel10MouseMoved

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        FIELDArea.setText("");
//        userName.setText("");
//        positionLabel.setText("");
//        position.setSelectedItem("Choose");
        FIELDArea.requestFocus();        
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        // TODO add your handling code here:
        HoverBar.setText("");
    }//GEN-LAST:event_jLabel10MouseExited

    private void submitBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnMouseMoved
        // TODO add your handling code here:
        HoverBar.setText("Submit");
    }//GEN-LAST:event_submitBtnMouseMoved

    private void submitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnMouseClicked

        if((FIELDArea.getText().isEmpty()) ||(userName.getText().isEmpty())){
                JOptionPane.showMessageDialog(this, "PLEASE TYPE MESSAGE");
            }
            else{
//                Nickname,'"+userName.getText()+"',
            try {
                String s = "UPDATE messageboard SET Message = '"+FIELDArea.getText()+"' , Position = '"+positionLabel.getText()+"' WHERE Nickname = '"+userName.getText()+"'";
                con.stmt.executeUpdate(s);
                JOptionPane.showMessageDialog(this, "POSTED!");
                FIELDArea.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(Message.class.getName()).log(Level.SEVERE, null, ex);
//                JOptionPane.showMessageDialog(this, userName);
            }
            }
    }//GEN-LAST:event_submitBtnMouseClicked

    private void submitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnMouseExited
        // TODO add your handling code here:
        HoverBar.setText("");
    }//GEN-LAST:event_submitBtnMouseExited

    private void cancelBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseMoved
        // TODO add your handling code here:
        HoverBar.setText("Cancel");
    }//GEN-LAST:event_cancelBtnMouseMoved

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
        // TODO add your handling code here:
        this.hide();
        //        Home home = new Home();
        new MainScreen().show();
    }//GEN-LAST:event_cancelBtnMouseClicked

    private void cancelBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseExited
        // TODO add your handling code here:
        HoverBar.setText("");
    }//GEN-LAST:event_cancelBtnMouseExited

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseEntered

    private void userNameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameMouseMoved
        // TODO add your handling code here:
        HoverBar.setText("ENTER NAME YOU WANT USERS TO SEE");
    }//GEN-LAST:event_userNameMouseMoved

    private void userNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameMouseExited
        // TODO add your handling code here:
        HoverBar.setText("");
    }//GEN-LAST:event_userNameMouseExited

    private void submitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_submitBtnMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Message().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FIELDArea;
    private javax.swing.JLabel HoverBar;
    private javax.swing.JLabel cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JTextField positionTxt;
    private javax.swing.JLabel submitBtn;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
